sonar.projectKey=neelp03_CMPE272-project
sonar.organization=neelp03

sonar.projectName=CMPE272-project
sonar.projectVersion=1.0

sonar.sources=.

sonar.exclusions=node_modules/**,dashboard/**,reports/**,coverage/**,**/*.test.js

sonar.language=js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
